apiVersion: v1
kind: Pod
metadata:
  name: pythonhelloworld.example.com
  labels:
    app: hellopython
spec:
  containers:
  - name: k8s-demo
    image: codemaniacguy/mypython-image
    ports:
    - name: python-port
      containerPort: 3000
